DATASET_CONFIGS = {
    "DROID":{
        "dataset_name": "DROID",
        "image_field": "wrist_image_left",
        "language_field": "language_instruction",
        "observation_field": "observation",
    },
    "dobb-e":{
        "dataset_name": "dobb-e",
        "image_field": "wrist_image",
        "language_field": "language_instruction",
        "observation_field": "observation",
        "max_episodes": None,
        "skip_frame": 1,
        "fps": 10,
    },
    "FMB": {
        "dataset_name": "FMB",
        "image_field": "image_side_1",
        "language_field": "language_instruction",
        "observation_field": "observation",
        "max_episodes": None,
        "skip_frame": 1,
        "fps": 10,
    },
    "IO-AI":{
        "dataset_name": "IO-AI",
        "image_field": "image",
        "language_field": "language_instruction",
        "observation_field": "observation",
        "max_episodes": None,
        "skip_frame": 1,
        "fps": 10,
    },
    "RoboSet":{
        "dataset_name": "RoboSet",
        "image_field": "image_left",
        "other_image_fields": [
            "image_top",
            "image_right",
            "image_wrist",
        ],
        "language_field": "language_instruction",
        "observation_field": "observation",
        "max_episodes": None,
        "skip_frame": 1,
        "fps": 20,
    },
    "UIUCD3Field":{
        "dataset_name": "UIUCD3Field",
        "image_field": "image_1",
        "language_field": "language_instruction",
        "observation_field": "observation",
        "max_episodes": None,
        "skip_frame": 1,
        "fps": 10,
    },
    "Austin Mutex":{
        "dataset_name": "Austin Mutex",
        "image_field": "image",
        "other_image_fields": [
            "wrist_image"
        ],
        "language_field": "language_instruction",
        "observation_field": "observation",
        "max_episodes": None,
        "skip_frame": 2,
        "fps": 25,
    },
    "Berkeley Fanuc Manipulation": {
        "dataset_name": "Berkeley Fanuc Manipulation",
        "image_field": "image",
        "language_field": "language_instruction",
        "observation_field": "observation",
        "fps": 10,
        "max_episodes": None,
        "skip_frame": 2,
    },
    "CMU Food Manipulation":{
        "dataset_name": "CMU Food Manipulation",
        "image_field": "image",
        "language_field": "language_instruction",
        "observation_field": "observation",
        "skip_frame": 1,
        "fps": 20,
        "max_episodes": None,
    },
    "CMU Play Fusion":{
        "dataset_name": "CMU Play Fusion",
        "image_field": "image",
        "language_field": "language_instruction",
        "observation_field": "observation",
        "skip_frame": 1,
        "fps": 20,
        "max_episodes": None,
    },
    "CMU Stretch":{
        "dataset_name": "CMU Stretch",
        "image_field": "image",
        "language_field": "language_instruction",
        "observation_field": "observation",
        "skip_frame": 1,
        "fps": 20,
        "max_episodes": 10,
    },
    "Mobile ALOHA":{
        "dataset_name": "Mobile ALOHA",
        "image_field": "cam_left_wrist",
        "language_field": "language_instruction",
        "observation_field": "observation",
        "skip_frame": 1,
        "fps": 20,
        "max_episodes": None,
    },
    "MimicPlay":{ 
        "dataset_name": "MimicPlay",
        "image_field": ("image", "front_image_1"),
        "language_field": "language_instruction",
        "observation_field": "observation",
        "skip_frame": 2,
        "fps": 20,
        "max_episodes": None,
    },
    "BridgeDataV2":{
        "dataset_name": "BridgeDataV2",
        "image_field": "image",
        "language_field": "natural_language_instruction",
        "observation_field": "observation",
        "skip_frame": 1,
        "fps": 10,
        "max_episodes": None,
    },
    "QT-Opt":{
        "dataset_name": "QT-Opt",
        "image_field": "image",
        "language_field": "language_instruction",
        "observation_field": "observation",
        "fps": 5,
        "max_episodes": None,
        "skip_frame": 1,
    },
    "RT-1 Robot Action":{
        "dataset_name": "RT-1 Robot Action",
        "image_field": "image",
        "other_image_fields": [
            "image_wrist"
        ],
        "language_field": "natural_language_instruction",
        "observation_field": "observation",
        "fps": 10,
        "max_episodes": None,
        "skip_frame": 1,
    },
    "NYU Franka Play":{
        "dataset_name": "NYU Franka Play",
        "image_field": "image",
        "other_image_fields": [
            "image_additional_view"
        ],
        "language_field": "language_instruction",
        "observation_field": "observation",
        "fps": 10,
        "max_episodes": None,
        "skip_frame": 1,
    },
    "Roboturk":{
        "dataset_name": "Roboturk",
        "image_field": "front_rgb",
        "language_field": "natural_language_instruction",
        "observation_field": "observation",
        "fps": 10,
        "max_episodes": None,
        "skip_frame": 1,
    },
    "Berkeley RPT Data":{
        "dataset_name": "Berkeley RPT Data",
        "image_field": "hand_image",
        "language_field": "language_instruction",
        "observation_field": "observation",
        "fps": 30,
        "max_episodes": None,
        "skip_frame": 1,
    },
    "BC-Z":{
        "dataset_name": "BC-Z",
        "image_field": "image",
        "language_field": "natural_language_instruction",
        "observation_field": "observation",
        "fps": 15,
        "max_episodes": None,
        "skip_frame": 2,
    },
    "USC Jaco Play":{
        "dataset_name": "USC Jaco Play",
        "image_field": "image",
        "other_image_fields": [
            "image_wrist"
        ],
        "language_field": "natural_language_instruction",
        "observation_field": "observation",
        "skip_frame": 1,
        "fps": 20,
        "max_episodes": None,
    },
    "Freiburg Franka Play":{
        "dataset_name": "Freiburg Franka Play",
        "image_field": "rgb_static",
        "other_image_fields": [
            "rgb_gripper"
        ],
        "language_field": "natural_language_instruction",
        "observation_field": "observation",
        "skip_frame": 1,
        "fps": 20,
        "max_episodes": None,
    },
    "UCSD Kitchen":{
        "dataset_name": "UCSD Kitchen",
        "image_field": "image",
        "language_field": "language_instruction",
        "observation_field": "observation",
        "skip_frame": 1,
        "fps": 8,
        "max_episodes": None,
    },
    "Berkeley MVP Data":{
        "dataset_name": "Berkeley MVP Data",
        "image_field": "hand_image",
        "language_field": "language_instruction",
        "observation_field": "observation",
        "skip_frame": 1,
        "fps": 40,
        "max_episodes": None,
    },
    "ASU TableTop Manipulation":{
        "dataset_name": "ASU TableTop Manipulation",
        "image_field": "image",
        "language_field": "language_instruction",
        "observation_field": "observation",
        "skip_frame": 1,
        "fps": 25,
        "max_episodes": None,
    },
    "KAIST Nonprehensile Objects":{
        "dataset_name": "KAIST Nonprehensile Objects",
        "image_field": "image",
        "language_field": "language_instruction",
        "observation_field": "observation",
        "skip_frame": 1,
        "fps": 20,
        "max_episodes": None,
    },
    
}

Local_dataset = [
    # "RT-1 Robot Action",
    # "NYU Franka Play",
    # "RoboSet",
    "BridgeDataV2"
    # "RoboSet",
    # "Roboturk",
    # "Berkeley RPT Data",
    # "BC-Z",
    # "CMU Play Fusion",
    # "Austin Mutex",
    # "USC Jaco Play",
    # "Freiburg Franka Play",
    # "UCSD Kitchen",
    # "Berkeley MVP Data",
    # "ASU TableTop Manipulation",
    # "KAIST Nonprehensile Objects"

]

Google_dataset = [
    # "Berkeley Fanuc Manipulation",
    # "dobb-e",
    # "MimicPlay",
    # "UIUCD3Field",
    # "IO-AI",
    # "CMU Stretch"

]


